INSERT INTO recipes (recipe_spell_id, item_id, profession, recipe, is_common, notes, tags)
VALUES
    (17635, 13510, 'Alchemy', 'Flask of the Titans', FALSE, 'Mandatory for main tanks, recommended for melee in Naxx', ARRAY['bwl/mc', 'aq40', 'naxx', 'tank', 'melee']),
    (17636, 13511, 'Alchemy', 'Flask of Distilled Wisdom', FALSE, 'Recommended for healers in Naxx', ARRAY['aq40', 'naxx', 'healer']),
    (17637, 13512, 'Alchemy', 'Flask of Supreme Power', FALSE, 'Recommended for casters in Naxx', ARRAY['aq40', 'naxx', 'caster']),
    (24365, 20007, 'Alchemy', 'Mageblood Potion', FALSE, 'Recommended for healers, optional for casters', ARRAY['healer', 'caster']),
    (17574, 13457, 'Alchemy', 'Greater Fire Protection Potion', FALSE, 'Used by Healers in BWL and Melee in Naxx', ARRAY['bwl/mc', 'naxx', 'fireresist', 'healer', 'melee']),
    (17576, 13458, 'Alchemy', 'Greater Nature Protection Potion', FALSE, 'Mandatory for AQ40 (Huhuran, Viscidus)', ARRAY['aq40', 'natureresist', 'caster', 'melee', 'healer', 'ranged']),
    (17575, 13456, 'Alchemy', 'Greater Frost Protection Potion', FALSE, 'Mandatory for Naxx (Sapphiron, KT)', ARRAY['naxx', 'frostresist', 'caster', 'melee', 'healer', 'ranged']),
    (17578, 13459, 'Alchemy', 'Greater Shadow Protection Potion', FALSE, 'Mandatory for Naxx (Four Horsemen, Loatheb)', ARRAY['naxx', 'caster', 'melee', 'healer', 'ranged']),
    (17577, 13461, 'Alchemy', 'Greater Arcane Protection Potion', FALSE, 'Recommended for by Melee in MC (Shazz) and Naxx (Gothik)', ARRAY['bwl/mc', 'naxx', 'melee']),
    (6624, 5634, 'Alchemy', 'Free Action Potion', TRUE, 'Every instance has a FAP pull for melee and tanks', ARRAY['tank', 'melee']),
    (3175, 3387, 'Alchemy', 'Limited Invulnerability Potion', FALSE, 'Used by Warriors for shout taunts, and casters for aggro triage', ARRAY['tank', 'melee', 'caster']),
    (17570, 13455, 'Alchemy', 'Greater Stoneshield Potion', FALSE, 'Used by all main tanks for all raids, and melee on dangerous fights', ARRAY['tank', 'melee']),
    (17552, 13442, 'Alchemy', 'Mighty Rage Potion', FALSE, 'Warrior BIS damage consumable', ARRAY['melee']),
    (17573, 13454, 'Alchemy', 'Greater Arcane Elixir', FALSE, 'BIS Caster Consume', ARRAY['caster']),
    (11472, 9206, 'Alchemy', 'Elixir of Giants', FALSE, 'Cheap consumable for melee', ARRAY['tank', 'melee']),
    (26277, 21546, 'Alchemy', 'Elixir of Greater Firepower', FALSE, 'Fire Mage BIS', ARRAY['caster']),
    (11476, 9264, 'Alchemy', 'Elixir of Shadow Power', TRUE, 'Warlock BIS', ARRAY['caster']),
    (17571, 13452, 'Alchemy', 'Elixir of the Mongoose', TRUE, 'Staple for all physical DPS in every raid', ARRAY['melee']),
    (23653, 19169, 'Blacksmithing', 'Nightfall', FALSE, 'Offtank, Shamans, or Hunter can craft this elite item', ARRAY['weapon', 'melee', 'ranged', 'healer']),
    (16729, 12640, 'Blacksmithing', 'Lionheart Helm', FALSE, 'BiS for fury warriors throughout all raid tiers', ARRAY['head', 'melee']),
    (23636, 19148, 'Blacksmithing', 'Dark Iron Helm', FALSE, 'Only Main Tanks needs this for a small number of fights', ARRAY['head', 'bwl/mc', 'naxx', 'tank', 'fireresist']),
    (24399, 20039, 'Blacksmithing', 'Dark Iron Boots', FALSE, 'Only Main Tanks needs this for a small number of fights', ARRAY['feet', 'bwl/mc', 'naxx', 'tank', 'fireresist']),
    (23637, 19164, 'Blacksmithing', 'Dark Iron Gauntlets', FALSE, 'Only Main Tanks needs this for a small number of fights', ARRAY['hands', 'bwl/mc', 'naxx', 'tank', 'fireresist']),
    (16741, 12639, 'Blacksmithing', 'Stronghold Gauntlets', FALSE, 'Anti-disarm gloves', ARRAY['hands', 'melee']),
    (27829, 22385, 'Blacksmithing', 'Titanic Leggings', FALSE, 'Fury warriors for all raids until AQ40/Naxx upgrades', ARRAY['legs', 'melee']),
    (20876, 17013, 'Blacksmithing', 'Dark Iron Leggings', FALSE, 'Only Main Tanks needs this for a small number of fights', ARRAY['legs', 'bwl/mc', 'naxx', 'tank', 'fireresist']),
    (20874, 17014, 'Blacksmithing', 'Dark Iron Bracers', FALSE, 'Only Main Tanks needs this for a small number of fights', ARRAY['wrist', 'bwl/mc', 'naxx', 'tank', 'fireresist']),
    (9964, 7969, 'Blacksmithing', 'Mithril Spurs', TRUE, 'Quality-of-life for all classes, not raid specific', ARRAY['qol']),
    (7222, 6043, 'Blacksmithing', 'Iron Counterweight', FALSE, 'Pair this with Nightfall specifically', ARRAY['melee']),
    (16651, 12645, 'Blacksmithing', 'Thorium Shield Spike', FALSE, 'This object uses a buff slot and should not be used in raids', ARRAY['shield', 'tank']),
    (22757, 18262, 'Blacksmithing', 'Elemental Sharpening Stone', FALSE, 'Used by Warriors on Offhand weapon and Hunters ', ARRAY['melee', 'ranged']),
    (20201, 16206, 'Blacksmithing', 'Arcanite Rod', TRUE, 'Crafting material for enchanting, not directly used in raids', ARRAY['component']),
    (16991, 12798, 'Blacksmithing', 'Annilhilator', FALSE, 'Offtank, Shamans, or Hunter can craft this elite item', ARRAY['weapon', 'melee', 'ranged', 'healer']),
    (27590, 22191, 'Blacksmithing', 'Obsidian Mail Tunic', FALSE, 'Alternative to farming Savage Gladiator Chain', ARRAY['chest', 'melee']),
    (20034, NULL, 'Enchanting', 'Enchant Weapon - Crusader', FALSE, 'Top enchant for melee DPS and tanks in all raids', ARRAY['tank', 'melee']),
    (22749, NULL, 'Enchanting', 'Enchant Weapon - Spellpower (+30)', FALSE, 'Essential for all caster DPS across all raid tiers', ARRAY['caster']),
    (22750, NULL, 'Enchanting', 'Enchant Weapon - Healing Power (+55)', FALSE, 'BiS for all healers throughout all raid content', ARRAY['healer']),
    (23800, NULL, 'Enchanting', 'Enchant Weapon - Agility (+15)', FALSE, 'Used by hunters for all raid content, situational offhand enchant for melee', ARRAY['melee', 'ranged']),
    (27837, NULL, 'Enchanting', 'Enchant 2H Weapon - Agility (+25)', FALSE, 'Used by hunters for all raid content', ARRAY['ranged']),
    (25086, NULL, 'Enchanting', 'Enchant Cloak - Dodge (+1%)', FALSE, 'Tanking enchant, situationally BIS', ARRAY['tank']),
    (13657, NULL, 'Enchanting', 'Enchant Cloak - Fire Resistance (+7)', TRUE, 'Typically paired with Onyxia Scale Cloak', ARRAY['bwl/mc', 'fireresist']),
    (25082, NULL, 'Enchanting', 'Enchant Cloak - Greater Nature Resistance (+15)', FALSE, 'Nature Resist for Soakers, pair with Gaea''s Embrace', ARRAY['aq40', 'natureresist']),
    (25084, NULL, 'Enchanting', 'Enchant Cloak - Subtlety', FALSE, 'Arguably BIS, depends on your damage', ARRAY['caster', 'melee']),
    (13882, NULL, 'Enchanting', 'Enchant Cloak - Lesser Agility (+3)', FALSE, 'BIS melee/hunter DPS enchant', ARRAY['melee', 'ranged']),
    (20014, NULL, 'Enchanting', 'Enchant Cloak - Greater Resistance (+5 all)', FALSE, 'General resistance enchant for most classes', ARRAY['caster', 'melee', 'healer', 'ranged', 'fireresist', 'natureresist', 'frostresist']),
    (20025, NULL, 'Enchanting', 'Enchant Chest - Greater Stats (+4)', FALSE, 'BiS for all classes across all raid tiers', ARRAY['tank', 'caster', 'melee', 'healer', 'ranged']),
    (20026, NULL, 'Enchanting', 'Enchant Chest - Major Health (+100)', FALSE, 'Preferred enchantment for resist gear', ARRAY['fireresist', 'natureresist', 'frostresist']),
    (20028, NULL, 'Enchanting', 'Enchant Chest - Major Mana (+100)', FALSE, 'Alternative for healers and casters', ARRAY['healer', 'caster']),
    (13941, NULL, 'Enchanting', 'Enchant Chest - Stats (+3)', TRUE, 'Budget option for chest', ARRAY['tank', 'caster', 'melee', 'healer', 'ranged']),
    (20023, NULL, 'Enchanting', 'Enchant Boots - Greater Agility (+7)', FALSE, 'Arguably BIS agility class enchant', ARRAY['melee', 'ranged']),
    (20020, NULL, 'Enchanting', 'Enchant Boots - Greater Stamina (+7)', FALSE, 'Arguably BIS for all classes', ARRAY['tank', 'caster', 'melee', 'healer', 'ranged']),
    (13890, NULL, 'Enchanting', 'Enchant Boots - Minor Speed', TRUE, 'Arguably BIS for all non-agility classes', ARRAY['tank', 'caster', 'healer']),
    (25080, NULL, 'Enchanting', 'Enchant Gloves - Superior Agility (+15)', FALSE, 'BIS for Hunter/Rogue and Tanks', ARRAY['melee', 'ranged', 'tank']),
    (25073, NULL, 'Enchanting', 'Enchant Gloves - Shadow Power (+20)', FALSE, 'Warlock BIS enchantment', ARRAY['caster']),
    (25079, NULL, 'Enchanting', 'Enchant Gloves - Healing Power (+30)', FALSE, 'Healer BIS enchantment', ARRAY['healer']),
    (25078, NULL, 'Enchanting', 'Enchant Gloves - Fire Power (+20)', FALSE, 'Mages for AQ40 and later Fire Spec', ARRAY['caster']),
    (20017, NULL, 'Enchanting', 'Enchant Shield - Greater Stamina (+7)', FALSE, 'Warrior and Shaman BIS', ARRAY['tank']),
    (23802, NULL, 'Enchanting', 'Enchant Bracer - Healing Power (+24)', FALSE, 'BiS for all healers in every raid', ARRAY['healer']),
    (23801, NULL, 'Enchanting', 'Enchant Bracer - Mana Regeneration (+4)', FALSE, 'Alternative for healers in mana-intensive fights', ARRAY['healer', 'caster']),
    (20011, NULL, 'Enchanting', 'Enchant Bracer - Superior Stamina (+9)', FALSE, 'Tanks enchantment, also preferred on resistance gear', ARRAY['tank', 'fireresist', 'natureresist', 'frostresist']),
    (20010, NULL, 'Enchanting', 'Enchant Bracer - Superior Strength (+9)', FALSE, 'Warrior/Rogue BIS', ARRAY['tank', 'melee']),
    (25130, 20748, 'Enchanting', 'Brilliant Mana Oil', FALSE, 'BIS for healers', ARRAY['healer']),
    (17181, 12810, 'Enchanting', 'Enchanted Leather', TRUE, 'Crafting material, not directly used in raids', ARRAY['component']),
    (17180, 12655, 'Enchanting', 'Enchanted Thorium', TRUE, 'Crafting material, not directly used in raids', ARRAY['component']),
    (25129, 20749, 'Enchanting', 'Brilliant Wizard Oil', FALSE, 'BIS for casters', ARRAY['caster']),
    (22793, 18283, 'Engineering', 'Biznicks 247x128 Accurascope', FALSE, 'BIS Hunter enchant', ARRAY['ranged']),
    (22797, 18168, 'Engineering', 'Force Reactive Disk', FALSE, 'Niche use for AoE tanking in MC (Garr adds)', ARRAY['shield', 'bwl/mc', 'tank']),
    (28208, 22658, 'Tailoring', 'Glacial Cloak', FALSE, 'ALL CLASSES for Naxx (Sapphiron)', ARRAY['back', 'naxx', 'caster', 'healer', 'ranged', 'melee', 'frostresist']),
    (28207, 22652, 'Tailoring', 'Glacial Vest', FALSE, 'Casters and Healers for Naxx (Sapphiron)', ARRAY['chest', 'naxx', 'caster', 'healer', 'frostresist', 'ranged', 'melee']),
    (28205, 22654, 'Tailoring', 'Glacial Gloves', FALSE, 'Casters and Healers for Naxx (Sapphiron)', ARRAY['hands', 'naxx', 'caster', 'healer', 'frostresist', 'ranged', 'melee']),
    (28209, 22655, 'Tailoring', 'Glacial Wrists', FALSE, 'Casters and Healers for Naxx (Sapphiron)', ARRAY['wrist', 'naxx', 'caster', 'healer', 'frostresist', 'ranged', 'melee']),
    (28210, 22660, 'Tailoring', 'Gaea''s Embrace', FALSE, 'Required for AQ40 (Huhuran, Viscidus) by ALL CLASSES', ARRAY['back', 'aq40', 'natureresist', 'caster', 'healer', 'ranged', 'melee']),
    (28481, 22757, 'Tailoring', 'Sylvan Crown', FALSE, 'Required for AQ40 (Huhuran, Viscidus) by ALL CLASSES', ARRAY['head', 'aq40', 'natureresist', 'caster', 'healer', 'ranged', 'melee']),
    (28482, 22758, 'Tailoring', 'Sylvan Shoulders', FALSE, 'Required for AQ40 (Huhuran, Viscidus) by ALL CLASSES', ARRAY['shoulders', 'aq40', 'natureresist', 'caster', 'healer', 'ranged', 'melee']),
    (28480, 22756, 'Tailoring', 'Sylvan Vest', FALSE, 'Required for AQ40 (Huhuran, Viscidus) by ALL CLASSES', ARRAY['chest', 'aq40', 'natureresist', 'caster', 'healer', 'ranged', 'melee']),
    (18418, 14044, 'Tailoring', 'Cindercloth Cloak', FALSE, 'Component for Onyxia Scale Cloak', ARRAY['back', 'bwl/mc', 'component']),
    (24091, 19682, 'Tailoring', 'Bloodvine Vest', FALSE, 'BiS for most casters in ZG/MC/BWL phase', ARRAY['chest', 'caster']),
    (24093, 19684, 'Tailoring', 'Bloodvine Boots', FALSE, 'BiS for most casters in ZG/MC/BWL phase', ARRAY['feet', 'caster']),
    (24092, 19683, 'Tailoring', 'Bloodvine Leggings', FALSE, 'BiS for most casters in ZG/MC/BWL phase', ARRAY['legs', 'caster']),
    (24902, 20539, 'Tailoring', 'Runed Stygian Belt', FALSE, 'Warlock Tanking gear for AQ40 (Twin Emperors)', ARRAY['waist', 'aq40', 'caster']),
    (24903, 20537, 'Tailoring', 'Runed Stygian Boots', FALSE, 'Warlock Tanking gear for AQ40 (Twin Emperors)', ARRAY['feet', 'aq40', 'caster']),
    (24901, 20538, 'Tailoring', 'Runed Stygian Leggings', FALSE, 'Warlock Tanking gear for AQ40 (Twin Emperors)', ARRAY['legs', 'aq40', 'caster']),
    (18445, 14155, 'Tailoring', 'Mooncloth Bag', FALSE, 'Cheap 16-slot bag', ARRAY['qol']),
    (18455, 14156, 'Tailoring', 'Bottomless Bag', FALSE, 'Largest bag in the game', ARRAY['qol']),
    (26087, 21342, 'Tailoring', 'Core Felcloth Bag', FALSE, 'Quality-of-life item for Warlocks', ARRAY['caster', 'qol']),
    (22927, 18510, 'Leatherworking', 'Hide of the Wild', FALSE, 'BiS for healers throughout most raid tiers', ARRAY['back', 'healer']),
    (19093, 15138, 'Leatherworking', 'Onyxia Scale Cloak', FALSE, 'Required for all raiders for BWL', ARRAY['back', 'bwl/mc', 'fireresist']),
    (28219, 22661, 'Leatherworking', 'Polar Tunic', FALSE, 'Required for Rogues in Naxx (Sapphiron)', ARRAY['chest', 'naxx', 'frostresist', 'melee']),
    (28220, 22662, 'Leatherworking', 'Polar Gloves', FALSE, 'Required for Rogues in Naxx (Sapphiron)', ARRAY['hands', 'naxx', 'frostresist', 'melee']),
    (28221, 22663, 'Leatherworking', 'Polar Bracers', FALSE, 'Required for Rogues in Naxx (Sapphiron)', ARRAY['wrist', 'naxx', 'frostresist', 'melee']),
    (23709, 19162, 'Leatherworking', 'Corehound Belt', FALSE, 'BiS for Shamans and Druids throughout most raid tiers', ARRAY['waist', 'healer']),
    (22727, 18251, 'Leatherworking', 'Core Armor Kit', FALSE, 'For aspiring Feral Tanks specifically', ARRAY['tank']),
    (23190, 18662, 'Leatherworking', 'Heavy Leather Ball', TRUE, 'Grief your friends!', ARRAY['qol']),
    (28222, 22664, 'Leatherworking', 'Icy Scale Breastplate', FALSE, 'Required for Warriors and Hunters in Naxx (Sapphiron)', ARRAY['chest', 'naxx', 'ranged', 'melee', 'frostresist']),
    (28223, 22666, 'Leatherworking', 'Icy Scale Gauntlets', FALSE, 'Required for Warriors and Hunters in Naxx (Sapphiron)', ARRAY['hands', 'naxx', 'ranged', 'melee', 'frostresist']),
    (28224, 22665, 'Leatherworking', 'Icy Scale Bracers', FALSE, 'Required for Warriors and Hunters in Naxx (Sapphiron)', ARRAY['wrist', 'naxx', 'ranged', 'melee', 'frostresist']),
    (25081, NULL, 'Enchanting', 'Enchant Cloak - Greater Fire Resistance (+15)', FALSE, 'Typically paired with Onyxia Scale Cloak', ARRAY['bwl/mc', 'fireresist']),
    (3872, 4335, 'Tailoring', 'Rich Purple Silk Shirt', FALSE, 'BiS drip for all characters', ARRAY['qol']),
    (25074, NULL, 'Enchanting', 'Enchant Gloves - Frost Power (+20)', FALSE, 'Frost Mage BiS', ARRAY['caster']),
    (13933, NULL, 'Enchanting', 'Enchant Shield - Frost Resistance (+8)', FALSE, 'Helpful for Naxx Tanks (Sapphiron, KT)', ARRAY['naxx', 'tank', 'frostresist']),
    (13689, NULL, 'Enchanting', 'Enchant Shield - Lesser Block (+2%)', FALSE, 'More block means less death. In theory.', ARRAY['tank']),
    (23803, NULL, 'Enchanting', 'Enchant Weapon - Mighty Spirit (+20)', FALSE, 'Evocate BiS', ARRAY['healer']),
    (23804, NULL, 'Enchanting', 'Enchant Weapon - Mighty Intellect (+22)', FALSE, 'Alternative for casters/healers vs. +sp or +hp', ARRAY['caster', 'healer']),
    (25659, 21023, 'Cooking', 'Dirge''s Kickin'' Chimaerok Chops', FALSE, 'BiS food for endgame tanking', ARRAY['tank', 'aq40', 'naxx']),
    (27660, 22249, 'Tailoring', 'Big Bag of Enchantment', FALSE, 'It''d be easier to vendor your low-level enchant mats. But just in case...', ARRAY['qol']),
    (27725, 22252, 'Tailoring', 'Satchel of Cenarius', FALSE, 'Holds herbs. Handy.', ARRAY['qol']),
    (8238, 6657, 'Cooking', 'Savory Deviate Delight', FALSE, 'Yarr or *silence*', ARRAY['pirate', 'ninja']),
    (12081, 10030, 'Tailoring', 'Admiral''s Hat', FALSE, 'BiS Yarr.', ARRAY['pirate'])
ON CONFLICT (recipe_spell_id) DO NOTHING;
